### ISSUE TITLE
hbc-twitter4j-2.2.1-SNAPSHOT-PROXY dependency not valid

### ISSUE THREAD

**Issue by saisubramaniam** [simonellistonball/nifi-GetTwitterWithProxy#1]
Hi @simonellistonball ,

Thanks for the initiative.

I am facing missing dependency error in the following
        <dependency>
            <groupId>com.twitter</groupId>
            <artifactId>hbc-twitter4j</artifactId>
            <version>2.2.1-SNAPSHOT-PROXY</version>
        </dependency>

This version is available in the maven central. Can you tell me where to find the custom jar (if there is one)? 
Can you pls upload the nar otherwise?

Thanks.

**Comment by simonellistonball** [comment]
You need to build this yourself following the instructions in the readme. Note that this is not a released version of hbc, it is a build of a fork on the official hbc, which adds the proxy support to twitter’s client. They have yet to accept the PR for proxy support, hence you need a private build, locally installed to the build machine with mvn install.

Simon

**Comment by saisubramaniam** [comment]
Thanks for the reply. I built the custom version of hbc and even built the nar.

When I try to authenticate I get the following error (attached)

My guess is that since the API request is https and the code is using httpclient without option for SSL certificate handling feature. Please correct me if I am wrong.

I believe it works for you, so can you suggest any debugging options to figure out the cause? I've double checked the auth keys.

Thanks!

![twitter_proxy_error](https://cloud.githubusercontent.com/assets/19303990/17182056/dd9f37c0-543f-11e6-97f0-0c912054ee44.png)

**Comment by simonellistonball** [comment]
This sounds like it's more to do with either missing the keys for the twitter application, or it may be a problem with not authenticating to the proxy. What do you get in your proxy logs? Not that at the moment only basic auth against the proxy is supported. Let me know if you need anything else.
